module.exports = {
  ADD_SEARCH: 'ADD_SEARCH',
  ADD_ALBUM: 'ADD_ALBUM',
  ADD_RELEASE: 'ADD_RELEASE',
  RESULTS: 'RESULTS',
  ADD_RELEASE_RESULTS: 'ADD_RELEASE_RESULTS',
  REMOVE_SEARCH: 'REMOVE_SEARCH',
  REMOVE_RELEASE_RESULTS: 'REMOVE_RELEASE_RESULTS',
  REMOVE_RELEASES: 'REMOVE_RELEASES',
};
