module.exports = {
  ADD_SEARCH: 'ADD_SEARCH',
  ADD_ALBUM: 'ADD_ALBUM',
  ADD_RELEASE: 'ADD_RELEASE',
  RESULTS: 'RESULTS',
  ADD_MASTER_RESULTS: 'ADD_MASTER_RESULTS',
  ADD_RELEASE_RESULTS: 'ADD_RELEASE_RESULTS',
};